export const JOB_DETAIL_TEXT = {
  tabs: {
    wof: "WOF",
    mechanical: "机修",
    paint: "喷漆",
    log: "Log",
    invoice: "Invoice",
  },
  empty: {
    noData: "没有任何数据",
    noLogs: "还没有日志记录。",
    noInvoiceItems: "暂无发票明细。",
  },
  buttons: {
    add: "添加",
    save: "保存",
    archive: "归档",
    delete: "删除",
    openNzta: "Open NZTA",
    refresh: "刷新",
    saveResult: "保存",
    print: "打印",
    linked: "Linked",
  },
  labels: {
    jobDetail: "Job Detail",
    vehicle: "汽车详细信息",
    customer: "客户详细信息",
    transactionId: "Transaction ID",
    urgent: "紧急",
    wofRecords: "WOF 记录",
    result: "结果",
    initiateResult: "Result",
    expiryDate: "Expiry Recheck Date",
    failReason: "Fail Reason",
    note: "Note",
    infoTitle: "Information",
    infoSubtitle: "Vehicle & Customer Details",
    vehicleDetails: "Vehicle Details",
    customerDetails: "Customer Details",
    plateNumber: "Plate Number",
    makeModel: "Make & Model",
    year: "Year",
    wof: "WOF",
    type: "Type",
    name: "Name",
    phone: "Phone",
    email: "Email",
    invoiceItems: "Invoice Items",
    linkToTransaction: "Link to Transaction",
  },
} as const;
