export const JOB_DETAIL_TEXT = {
  tabs: {
    wof: "WOF",
    mechanical: "Machine repair",
    parts: "Accessories",
    paint: "spray paint",
    worklog: "working hours",
    log: "Log",
    invoice: "Invoice",
    po: "PO",
  },
  empty: {
    noData: "no data",
    noLogs: "No logging yet.",
    noInvoiceItems: "There are no invoice details yet.",
  },
  buttons: {
    add: "Add to",
    save: "save",
    archive: "Archive",
    delete: "delete",
    openNzta: "Open NZTA",
    refresh: "refresh",
    saveResult: "save",
    print: "Print",
    linked: "Linked",
  },
  labels: {
    jobDetail: "Job Detail",
    vehicle: "car details",
    customer: "Customer details",
    transactionId: "Transaction ID",
    urgent: "urgent",
    wofRecords: "WOF record",
    result: "result",
    initiateResult: "Result",
    expiryDate: "Expiry Recheck Date",
    failReason: "Fail Reason",
    note: "Note",
    infoTitle: "Information",
    infoSubtitle: "Vehicle & Customer Details",
    vehicleDetails: "Vehicle Details",
    customerDetails: "Customer Details",
    plateNumber: "Plate Number",
    makeModel: "Make & Model",
    year: "Year",
    wof: "WOF",
    type: "Type",
    name: "Name",
    phone: "Phone",
    email: "Email",
    invoiceItems: "Invoice Items",
    linkToTransaction: "Link to Transaction",
  },
} as const;
