using Workshop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Workshop.Api.Services;

public sealed class PoStateSchemaInitializerService : IHostedService
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly ILogger<PoStateSchemaInitializerService> _logger;

    public PoStateSchemaInitializerService(
        IServiceScopeFactory scopeFactory,
        ILogger<PoStateSchemaInitializerService> logger)
    {
        _scopeFactory = scopeFactory;
        _logger = logger;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        using var scope = _scopeFactory.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var inventoryItemService = scope.ServiceProvider.GetRequiredService<InventoryItemService>();
        var poStateService = scope.ServiceProvider.GetRequiredService<JobPoStateService>();

        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE jobs ADD COLUMN IF NOT EXISTS po_number text;
                ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_reference text;

                CREATE TABLE IF NOT EXISTS gmail_accounts (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email text NOT NULL,
                    refresh_token text NOT NULL,
                    access_token text NULL,
                    access_token_expires_at timestamptz NULL,
                    scope text NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    is_default boolean NOT NULL DEFAULT false,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_gmail_accounts_email ON gmail_accounts(email);
                CREATE INDEX IF NOT EXISTS ix_gmail_accounts_is_default ON gmail_accounts(is_default);

                CREATE TABLE IF NOT EXISTS gmail_message_logs (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    gmail_account_id bigint NULL,
                    gmail_account_email text NULL,
                    gmail_message_id text NOT NULL,
                    gmail_thread_id text NULL,
                    internal_date_ms bigint NULL,
                    direction text NOT NULL,
                    counterparty_email text NOT NULL,
                    from_address text NULL,
                    to_address text NULL,
                    subject text NULL,
                    body text NULL,
                    snippet text NULL,
                    correlation_id text NULL,
                    rfc_message_id text NULL,
                    references_header text NULL,
                    has_attachments boolean NOT NULL DEFAULT false,
                    attachments_json text NULL,
                    is_read boolean NOT NULL DEFAULT false,
                    read_at timestamptz NULL,
                    detected_po_number text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS gmail_account_id bigint NULL;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS gmail_account_email text NULL;
                DROP INDEX IF EXISTS ux_gmail_message_logs_message_id;
                CREATE UNIQUE INDEX IF NOT EXISTS ux_gmail_message_logs_account_message_id ON gmail_message_logs(gmail_account_id, gmail_message_id);
                CREATE INDEX IF NOT EXISTS ix_gmail_message_logs_account_id ON gmail_message_logs(gmail_account_id);
                CREATE INDEX IF NOT EXISTS ix_gmail_message_logs_thread_id ON gmail_message_logs(gmail_thread_id);
                CREATE INDEX IF NOT EXISTS ix_gmail_message_logs_correlation_id ON gmail_message_logs(correlation_id);

                CREATE TABLE IF NOT EXISTS inactive_gmail_correlations (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    correlation_id text NOT NULL,
                    reason text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_inactive_gmail_correlations_correlation_id
                    ON inactive_gmail_correlations(correlation_id);

                CREATE TABLE IF NOT EXISTS job_invoices (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id bigint NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                    provider text NOT NULL,
                    external_invoice_id text NULL,
                    external_invoice_number text NULL,
                    external_status text NULL,
                    reference text NULL,
                    contact_name text NULL,
                    invoice_date date NULL,
                    line_amount_types text NOT NULL,
                    tenant_id text NULL,
                    request_payload_json text NULL,
                    response_payload_json text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_job_invoices_job_id ON job_invoices(job_id);

                CREATE TABLE IF NOT EXISTS job_payments (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id bigint NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                    job_invoice_id bigint NOT NULL REFERENCES job_invoices(id) ON DELETE CASCADE,
                    provider text NOT NULL,
                    external_payment_id text NULL,
                    external_invoice_id text NULL,
                    method text NOT NULL,
                    amount numeric NOT NULL,
                    payment_date date NOT NULL,
                    reference text NULL,
                    account_code text NULL,
                    account_name text NULL,
                    external_status text NULL,
                    request_payload_json text NULL,
                    response_payload_json text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE INDEX IF NOT EXISTS ix_job_payments_job_id ON job_payments(job_id);
                CREATE INDEX IF NOT EXISTS ix_job_payments_job_invoice_id ON job_payments(job_invoice_id);

                CREATE TABLE IF NOT EXISTS xero_tokens (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    provider text NOT NULL,
                    refresh_token text NOT NULL,
                    access_token text NULL,
                    access_token_expires_at timestamptz NULL,
                    scope text NULL,
                    tenant_id text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_xero_tokens_provider ON xero_tokens(provider);

                CREATE TABLE IF NOT EXISTS inventory_items (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_code text NOT NULL,
                    item_name text NOT NULL,
                    quantity numeric NULL,
                    purchases_description text NULL,
                    purchases_unit_price numeric NULL,
                    purchases_account text NULL,
                    purchases_tax_rate text NULL,
                    sales_description text NULL,
                    sales_unit_price numeric NULL,
                    sales_account text NULL,
                    sales_tax_rate text NULL,
                    inventory_asset_account text NULL,
                    cost_of_goods_sold_account text NULL,
                    status text NOT NULL,
                    inventory_type text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_items_item_code ON inventory_items(item_code);
                CREATE INDEX IF NOT EXISTS ix_inventory_items_item_name ON inventory_items(item_name);

                CREATE TABLE IF NOT EXISTS system_sync_state (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sync_key text NOT NULL,
                    last_synced_at timestamptz NULL,
                    last_result text NULL,
                    last_error text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_system_sync_state_sync_key ON system_sync_state(sync_key);

                CREATE TABLE IF NOT EXISTS job_po_state (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id bigint NOT NULL,
                    correlation_id text NOT NULL,
                    counterparty_email text NULL,
                    status text NOT NULL,
                    requires_admin_attention boolean NOT NULL DEFAULT false,
                    admin_attention_reason text NULL,
                    confirmed_po_number text NULL,
                    detected_po_number text NULL,
                    first_request_sent_at timestamptz NULL,
                    last_request_sent_at timestamptz NULL,
                    last_follow_up_sent_at timestamptz NULL,
                    last_supplier_reply_at timestamptz NULL,
                    last_supplier_reply_message_id text NULL,
                    follow_up_count integer NOT NULL DEFAULT 0,
                    follow_up_enabled boolean NOT NULL DEFAULT true,
                    next_follow_up_due_at timestamptz NULL,
                    last_synced_at timestamptz NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_job_po_state_job_id ON job_po_state(job_id);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_status ON job_po_state(status);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_correlation_id ON job_po_state(correlation_id);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_next_follow_up_due_at ON job_po_state(next_follow_up_due_at);

                ALTER TABLE wof_fail_reasons ADD COLUMN IF NOT EXISTS code text;
                """);

            await inventoryItemService.EnsureSeededAsync(cancellationToken);
            await poStateService.EnsureStatesForNeedsPoJobsAsync(cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to initialize PO state schema.");
            throw;
        }
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
