using Workshop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Workshop.Api.Services;

public sealed class PoStateSchemaInitializerService : IHostedService
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly ILogger<PoStateSchemaInitializerService> _logger;

    public PoStateSchemaInitializerService(
        IServiceScopeFactory scopeFactory,
        ILogger<PoStateSchemaInitializerService> logger)
    {
        _scopeFactory = scopeFactory;
        _logger = logger;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        using var scope = _scopeFactory.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var poStateService = scope.ServiceProvider.GetRequiredService<JobPoStateService>();

        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE jobs ADD COLUMN IF NOT EXISTS po_number text;
                ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_reference text;

                CREATE TABLE IF NOT EXISTS job_po_state (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id bigint NOT NULL,
                    correlation_id text NOT NULL,
                    counterparty_email text NULL,
                    status text NOT NULL,
                    requires_admin_attention boolean NOT NULL DEFAULT false,
                    admin_attention_reason text NULL,
                    confirmed_po_number text NULL,
                    detected_po_number text NULL,
                    first_request_sent_at timestamptz NULL,
                    last_request_sent_at timestamptz NULL,
                    last_follow_up_sent_at timestamptz NULL,
                    last_supplier_reply_at timestamptz NULL,
                    last_supplier_reply_message_id text NULL,
                    follow_up_count integer NOT NULL DEFAULT 0,
                    follow_up_enabled boolean NOT NULL DEFAULT true,
                    next_follow_up_due_at timestamptz NULL,
                    last_synced_at timestamptz NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_job_po_state_job_id ON job_po_state(job_id);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_status ON job_po_state(status);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_correlation_id ON job_po_state(correlation_id);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_next_follow_up_due_at ON job_po_state(next_follow_up_due_at);
                """);

            await poStateService.EnsureStatesForNeedsPoJobsAsync(cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to initialize PO state schema.");
            throw;
        }
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
