namespace Workshop.Api.DTOs;

public sealed record CourtesyCarVehicleDto(
    long Id,
    string Plate,
    string? Make,
    string? Model,
    string? Color,
    int? Year,
    int? Mileage,
    string? FuelLevel,
    decimal AgreedVehicleValue,
    string Status,
    string? Note,
    DateOnly? WofExpiry,
    DateOnly? RegoExpiry,
    DateTime? ReturnedAt,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public sealed record CourtesyCarAgreementAttachmentDto(
    string Id,
    string Kind,
    string Name,
    string MimeType,
    long Size,
    string DownloadUrl,
    DateTime CreatedAt);

public sealed record CourtesyCarAgreementEventDto(
    long Id,
    string EventType,
    string? ActorType,
    string? ActorName,
    string? PayloadJson,
    DateTime CreatedAt);

public sealed record CourtesyCarAgreementPreviewValidationDto(
    long AgreementId,
    bool IsValid,
    string? Message);

public sealed record CourtesyCarAgreementListItemDto(
    long Id,
    long JobId,
    string? JobVehiclePlate,
    string? JobCustomerName,
    string? JobCustomerPhone,
    string? JobCustomerEmail,
    string? JobCustomerAddress,
    long? VehicleId,
    string? VehiclePlate,
    string? VehicleMake,
    string? VehicleModel,
    string Status,
    string CurrentStep,
    DateTime? SubmittedAt,
    DateTime? ClosedAt,
    DateTime? CancelledAt,
    DateTime? EmailSentAt,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public sealed record CourtesyCarAgreementDetailDto(
    long Id,
    long JobId,
    long? VehicleId,
    long? CustomerId,
    string Status,
    string CurrentStep,
    string? JobVehiclePlate,
    string? JobCustomerName,
    string? JobCustomerPhone,
    string? JobCustomerEmail,
    string? JobCustomerAddress,
    string? ContactName,
    string? ContactPhone,
    string? ContactEmail,
    string? ContactAddress,
    string? DriverLicenseNumber,
    DateOnly? DriverLicenseExpiry,
    string? EmergencyContactName,
    string? EmergencyContactPhone,
    bool TermsConfirmed,
    string? SignatureName,
    string? VehiclePlate,
    string? VehicleMake,
    string? VehicleModel,
    string? VehicleColor,
    int? VehicleYear,
    int? VehicleMileage,
    string? VehicleFuelLevel,
    decimal AgreedVehicleValue,
    DateOnly? VehicleWofExpiry,
    DateOnly? VehicleRegoExpiry,
    IReadOnlyList<CourtesyCarAgreementAttachmentDto> Attachments,
    IReadOnlyList<CourtesyCarAgreementEventDto> Events,
    string? PdfUrl,
    DateTime? PdfGeneratedAt,
    DateTime? EmailSentAt,
    string? EmailTo,
    string? EmailMessageId,
    DateTime? SubmittedAt,
    DateTime? ClosedAt,
    DateTime? CancelledAt,
    DateTime CreatedAt,
    DateTime UpdatedAt);
