using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Workshop.Api.Data;

#nullable disable

namespace Workshop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701090000_AddJobLightBindings")]
    public partial class AddJobLightBindings : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS job_light_bindings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                    plate VARCHAR(32) NOT NULL,
                    station_id VARCHAR(32) NOT NULL,
                    tag_id VARCHAR(32) NOT NULL,
                    group_no INTEGER NOT NULL,
                    status VARCHAR(40) NOT NULL DEFAULT 'PendingBind',
                    failure_reason TEXT,
                    last_result_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_job_light_bindings_active_job_id
                    ON job_light_bindings (job_id)
                    WHERE status IN ('PendingBind', 'Bound');

                CREATE UNIQUE INDEX IF NOT EXISTS ux_job_light_bindings_active_tag_id
                    ON job_light_bindings (tag_id)
                    WHERE status IN ('PendingBind', 'Bound');

                CREATE INDEX IF NOT EXISTS ix_job_light_bindings_station_id ON job_light_bindings (station_id);
                CREATE INDEX IF NOT EXISTS ix_job_light_bindings_status ON job_light_bindings (status);
                CREATE INDEX IF NOT EXISTS ix_job_light_bindings_updated_at ON job_light_bindings (updated_at);
            """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS job_light_bindings;");
        }
    }
}
