using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Workshop.Api.Data;

#nullable disable

namespace Workshop.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260407120000_AddJobWofScheduleEntries")]
public partial class AddJobWofScheduleEntries : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS job_wof_schedule_entries (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id bigint NULL REFERENCES jobs(id) ON DELETE CASCADE,
                entry_type text NOT NULL,
                placeholder_key text NULL,
                scheduled_date date NULL,
                scheduled_hour integer NULL,
                rego text NULL,
                contact text NULL,
                notes text NULL,
                created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                CONSTRAINT ck_job_wof_schedule_entries_entry_type
                    CHECK (entry_type IN ('job', 'placeholder')),
                CONSTRAINT ck_job_wof_schedule_entries_slot_pair
                    CHECK (
                        (scheduled_date IS NULL AND scheduled_hour IS NULL)
                        OR (scheduled_date IS NOT NULL AND scheduled_hour IS NOT NULL)
                    ),
                CONSTRAINT ck_job_wof_schedule_entries_scheduled_hour
                    CHECK (scheduled_hour IS NULL OR (scheduled_hour >= 0 AND scheduled_hour <= 23)),
                CONSTRAINT ck_job_wof_schedule_entries_shape
                    CHECK (
                        (entry_type = 'job' AND job_id IS NOT NULL AND placeholder_key IS NULL)
                        OR (entry_type = 'placeholder' AND job_id IS NULL AND placeholder_key IS NOT NULL)
                    )
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ux_job_wof_schedule_entries_job_id
                ON job_wof_schedule_entries(job_id)
                WHERE job_id IS NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS ux_job_wof_schedule_entries_placeholder_key
                ON job_wof_schedule_entries(placeholder_key)
                WHERE placeholder_key IS NOT NULL;

            CREATE INDEX IF NOT EXISTS ix_job_wof_schedule_entries_slot
                ON job_wof_schedule_entries(scheduled_date, scheduled_hour);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS job_wof_schedule_entries;");
    }
}
