using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Workshop.Api.Data;

#nullable disable

namespace Workshop.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260718110000_AddWofCalendarRecords")]
public partial class AddWofCalendarRecords : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS wof_calendar_records (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_file text NOT NULL,
                excel_row_no integer NOT NULL,
                job_id bigint NULL REFERENCES jobs(id) ON DELETE SET NULL,
                occurred_at timestamptz NOT NULL,
                rego text NOT NULL,
                make_model text NULL,
                record_state wof_record_state NOT NULL,
                imported_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ux_wof_calendar_records_source_row
                ON wof_calendar_records(source_file, excel_row_no);

            CREATE INDEX IF NOT EXISTS ix_wof_calendar_records_occurred_at
                ON wof_calendar_records(occurred_at);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS wof_calendar_records;");
    }
}
