// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workshop.Api.Data;
using Workshop.Api.Models;

#nullable disable

namespace Workshop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329120523_EnforceSinglePaymentPerInvoice")]
    partial class EnforceSinglePaymentPerInvoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "parts_service_status", new[] { "pending_order", "needs_pt", "parts_trader", "pickup_or_transit" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "wof_record_state", new[] { "pass", "fail", "recheck" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "wof_ui_state", new[] { "pass", "fail", "recheck", "printed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "worklog_service_type", new[] { "pnp", "mech" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workshop.Api.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BusinessCode")
                        .HasColumnType("text")
                        .HasColumnName("business_code");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.CustomerServicePrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long>("ServiceCatalogItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_catalog_item_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("XeroItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xero_item_code");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_service_prices_customer_id");

                    b.HasIndex("ServiceCatalogItemId")
                        .HasDatabaseName("ix_customer_service_prices_service_catalog_item_id");

                    b.ToTable("customer_service_prices", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.CustomerStaff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_staff_customer_id");

                    b.ToTable("customer_staff", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.GmailAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_gmail_accounts_email");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("ix_gmail_accounts_is_default");

                    b.ToTable("gmail_accounts", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.GmailMessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("text")
                        .HasColumnName("attachments_json");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CounterpartyEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("counterparty_email");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("DetectedPoNumber")
                        .HasColumnType("text")
                        .HasColumnName("detected_po_number");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("FromAddress")
                        .HasColumnType("text")
                        .HasColumnName("from_address");

                    b.Property<string>("GmailAccountEmail")
                        .HasColumnType("text")
                        .HasColumnName("gmail_account_email");

                    b.Property<long?>("GmailAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("gmail_account_id");

                    b.Property<string>("GmailMessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gmail_message_id");

                    b.Property<string>("GmailThreadId")
                        .HasColumnType("text")
                        .HasColumnName("gmail_thread_id");

                    b.Property<bool>("HasAttachments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_attachments");

                    b.Property<long?>("InternalDateMs")
                        .HasColumnType("bigint")
                        .HasColumnName("internal_date_ms");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<bool>("IsSystemInitiated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_initiated");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("ReferencesHeader")
                        .HasColumnType("text")
                        .HasColumnName("references_header");

                    b.Property<string>("RfcMessageId")
                        .HasColumnType("text")
                        .HasColumnName("rfc_message_id");

                    b.Property<string>("Snippet")
                        .HasColumnType("text")
                        .HasColumnName("snippet");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("ToAddress")
                        .HasColumnType("text")
                        .HasColumnName("to_address");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_gmail_message_logs_correlation_id");

                    b.HasIndex("GmailAccountId")
                        .HasDatabaseName("ix_gmail_message_logs_account_id");

                    b.HasIndex("GmailThreadId")
                        .HasDatabaseName("ix_gmail_message_logs_thread_id");

                    b.HasIndex("GmailAccountId", "GmailMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_gmail_message_logs_account_message_id");

                    b.ToTable("gmail_message_logs", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.InactiveGmailCorrelation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("ux_inactive_gmail_correlations_correlation_id");

                    b.ToTable("inactive_gmail_correlations", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.InventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CostOfGoodsSoldAccount")
                        .HasColumnType("text")
                        .HasColumnName("cost_of_goods_sold_account");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("InventoryAssetAccount")
                        .HasColumnType("text")
                        .HasColumnName("inventory_asset_account");

                    b.Property<string>("InventoryType")
                        .HasColumnType("text")
                        .HasColumnName("inventory_type");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<string>("PurchasesAccount")
                        .HasColumnType("text")
                        .HasColumnName("purchases_account");

                    b.Property<string>("PurchasesDescription")
                        .HasColumnType("text")
                        .HasColumnName("purchases_description");

                    b.Property<string>("PurchasesTaxRate")
                        .HasColumnType("text")
                        .HasColumnName("purchases_tax_rate");

                    b.Property<decimal?>("PurchasesUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("purchases_unit_price");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("SalesAccount")
                        .HasColumnType("text")
                        .HasColumnName("sales_account");

                    b.Property<string>("SalesDescription")
                        .HasColumnType("text")
                        .HasColumnName("sales_description");

                    b.Property<string>("SalesTaxRate")
                        .HasColumnType("text")
                        .HasColumnName("sales_tax_rate");

                    b.Property<decimal?>("SalesUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sales_unit_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_items_item_code");

                    b.HasIndex("ItemName")
                        .HasDatabaseName("ix_inventory_items_item_name");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("InvoiceReference")
                        .HasColumnType("text")
                        .HasColumnName("invoice_reference");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_urgent");

                    b.Property<bool>("NeedsPo")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_po");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PoNumber")
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<bool>("UseServiceCatalogMapping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("use_service_catalog_mapping");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("ExternalInvoiceId")
                        .HasColumnType("text")
                        .HasColumnName("external_invoice_id");

                    b.Property<string>("ExternalInvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("external_invoice_number");

                    b.Property<string>("ExternalStatus")
                        .HasColumnType("text")
                        .HasColumnName("external_status");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNote")
                        .HasColumnType("text")
                        .HasColumnName("invoice_note");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("LineAmountTypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_amount_types");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("request_payload_json");

                    b.Property<string>("ResponsePayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("response_payload_json");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ux_job_invoices_job_id");

                    b.ToTable("job_invoices", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobMechService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.ToTable("job_mech_services", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobPaintService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<int>("CurrentStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1)
                        .HasColumnName("current_stage");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<int>("Panels")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("panels");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.ToTable("job_paint_services", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobPartsNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long>("PartsServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("parts_service_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.ToTable("job_parts_notes", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobPartsService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<PartsServiceStatus>("Status")
                        .HasColumnType("parts_service_status")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.ToTable("job_parts_services", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountCode")
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountName")
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("ExternalInvoiceId")
                        .HasColumnType("text")
                        .HasColumnName("external_invoice_id");

                    b.Property<string>("ExternalPaymentId")
                        .HasColumnType("text")
                        .HasColumnName("external_payment_id");

                    b.Property<string>("ExternalStatus")
                        .HasColumnType("text")
                        .HasColumnName("external_status");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<long>("JobInvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("request_payload_json");

                    b.Property<string>("ResponsePayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("response_payload_json");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_payments_job_id");

                    b.HasIndex("JobInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_job_payments_job_invoice_id");

                    b.ToTable("job_payments", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobPoState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminAttentionReason")
                        .HasColumnType("text")
                        .HasColumnName("admin_attention_reason");

                    b.Property<string>("ConfirmedPoNumber")
                        .HasColumnType("text")
                        .HasColumnName("confirmed_po_number");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CounterpartyEmail")
                        .HasColumnType("text")
                        .HasColumnName("counterparty_email");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("DetectedPoNumber")
                        .HasColumnType("text")
                        .HasColumnName("detected_po_number");

                    b.Property<DateTime?>("FirstRequestSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_request_sent_at");

                    b.Property<int>("FollowUpCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("follow_up_count");

                    b.Property<bool>("FollowUpEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("follow_up_enabled");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("LastFollowUpSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_follow_up_sent_at");

                    b.Property<DateTime?>("LastRequestSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_request_sent_at");

                    b.Property<DateTime?>("LastSupplierReplyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_supplier_reply_at");

                    b.Property<string>("LastSupplierReplyMessageId")
                        .HasColumnType("text")
                        .HasColumnName("last_supplier_reply_message_id");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTime?>("NextFollowUpDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_follow_up_due_at");

                    b.Property<bool>("RequiresAdminAttention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_admin_attention");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_job_po_state_correlation_id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ux_job_po_state_job_id");

                    b.HasIndex("NextFollowUpDueAt")
                        .HasDatabaseName("ix_job_po_state_next_follow_up_due_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_po_state_status");

                    b.ToTable("job_po_state", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobServiceSelection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<long>("ServiceCatalogItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_catalog_item_id");

                    b.Property<string>("ServiceNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name_snapshot");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_service_selections_job_id");

                    b.HasIndex("ServiceCatalogItemId")
                        .HasDatabaseName("ix_job_service_selections_service_catalog_item_id");

                    b.ToTable("job_service_selections", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobTag", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("JobId", "TagId");

                    b.ToTable("job_tags", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.JobWofRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthCode")
                        .HasColumnType("text")
                        .HasColumnName("auth_code");

                    b.Property<string>("CheckSheet")
                        .HasColumnType("text")
                        .HasColumnName("check_sheet");

                    b.Property<string>("CsNo")
                        .HasColumnType("text")
                        .HasColumnName("cs_no");

                    b.Property<int>("ExcelRowNo")
                        .HasColumnType("integer")
                        .HasColumnName("excel_row_no");

                    b.Property<string>("FailReasons")
                        .HasColumnType("text")
                        .HasColumnName("fail_reasons");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<bool?>("IsNewWof")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_wof");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("LabelNo")
                        .HasColumnType("text")
                        .HasColumnName("label_no");

                    b.Property<string>("MakeModel")
                        .HasColumnType("text")
                        .HasColumnName("make_model");

                    b.Property<DateOnly?>("NewWofDate")
                        .HasColumnType("date")
                        .HasColumnName("new_wof_date");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Odo")
                        .HasColumnType("text")
                        .HasColumnName("odo");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organisation_name");

                    b.Property<DateOnly?>("PreviousExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("previous_expiry_date");

                    b.Property<WofRecordState>("RecordState")
                        .HasColumnType("wof_record_state")
                        .HasColumnName("record_state");

                    b.Property<string>("Rego")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rego");

                    b.Property<string>("SourceFile")
                        .HasColumnType("text")
                        .HasColumnName("source_file");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("WofLabel")
                        .HasColumnType("text")
                        .HasColumnName("wof_label");

                    b.Property<WofUiState>("WofUiState")
                        .HasColumnType("wof_ui_state")
                        .HasColumnName("wof_ui_state");

                    b.HasKey("Id");

                    b.ToTable("job_wof_records", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.ServiceCatalogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("DealershipLinkCode")
                        .HasColumnType("text")
                        .HasColumnName("dealership_link_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PersonalLinkCode")
                        .HasColumnType("text")
                        .HasColumnName("personal_link_code");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("ServiceType", "Category")
                        .HasDatabaseName("ix_service_catalog_items_type_category");

                    b.ToTable("service_catalog_items", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.Staff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostRate")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_rate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.SystemSyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("LastResult")
                        .HasColumnType("text")
                        .HasColumnName("last_result");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("SyncKey")
                        .IsUnique()
                        .HasDatabaseName("ux_system_sync_state_sync_key");

                    b.ToTable("system_sync_state", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyStyle")
                        .HasColumnType("text")
                        .HasColumnName("body_style");

                    b.Property<int?>("CcRating")
                        .HasColumnType("integer")
                        .HasColumnName("cc_rating");

                    b.Property<string>("Chassis")
                        .HasColumnType("text")
                        .HasColumnName("chassis");

                    b.Property<string>("Colour")
                        .HasColumnType("text")
                        .HasColumnName("colour");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("text")
                        .HasColumnName("country_of_origin");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Engine")
                        .HasColumnType("text")
                        .HasColumnName("engine");

                    b.Property<string>("EngineNo")
                        .HasColumnType("text")
                        .HasColumnName("engine_no");

                    b.Property<decimal?>("FuelTankCapacityLitres")
                        .HasColumnType("numeric")
                        .HasColumnName("fuel_tank_capacity_litres");

                    b.Property<string>("FuelType")
                        .HasColumnType("text")
                        .HasColumnName("fuel_type");

                    b.Property<decimal?>("FullCombinedRangeKm")
                        .HasColumnType("numeric")
                        .HasColumnName("full_combined_range_km");

                    b.Property<int?>("GrossVehicleMass")
                        .HasColumnType("integer")
                        .HasColumnName("gross_vehicle_mass");

                    b.Property<string>("Make")
                        .HasColumnType("text")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<DateOnly?>("NzFirstRegistration")
                        .HasColumnType("date")
                        .HasColumnName("nz_first_registration");

                    b.Property<int?>("Odometer")
                        .HasColumnType("integer")
                        .HasColumnName("odometer");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plate");

                    b.Property<JsonDocument>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Refrigerant")
                        .HasColumnType("text")
                        .HasColumnName("refrigerant");

                    b.Property<DateOnly?>("RegoExpiry")
                        .HasColumnType("date")
                        .HasColumnName("rego_expiry");

                    b.Property<int?>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("Vin")
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<DateOnly?>("WofExpiry")
                        .HasColumnType("date")
                        .HasColumnName("wof_expiry");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.WofFailReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.ToTable("wof_fail_reasons", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.WofResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FailReasonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("RecheckExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WofId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WofResults");
                });

            modelBuilder.Entity("Workshop.Api.Models.WofService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.ToTable("wof_service", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.WorklogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin_note");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_time");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<WorklogServiceType>("ServiceType")
                        .HasColumnType("worklog_service_type")
                        .HasColumnName("service_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("work_date");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("StaffId");

                    b.ToTable("worklogs", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.XeroTokenRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TenantName")
                        .HasColumnType("text")
                        .HasColumnName("tenant_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("date_trunc('milliseconds', now())");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("ix_xero_tokens_is_default");

                    b.HasIndex("Provider", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_xero_tokens_provider_tenant_id");

                    b.ToTable("xero_tokens", (string)null);
                });

            modelBuilder.Entity("Workshop.Api.Models.CustomerServicePrice", b =>
                {
                    b.HasOne("Workshop.Api.Models.Customer", "Customer")
                        .WithMany("ServicePrices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workshop.Api.Models.ServiceCatalogItem", "ServiceCatalogItem")
                        .WithMany()
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ServiceCatalogItem");
                });

            modelBuilder.Entity("Workshop.Api.Models.CustomerStaff", b =>
                {
                    b.HasOne("Workshop.Api.Models.Customer", "Customer")
                        .WithMany("StaffMembers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Workshop.Api.Models.JobInvoice", b =>
                {
                    b.HasOne("Workshop.Api.Models.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workshop.Api.Models.JobPayment", b =>
                {
                    b.HasOne("Workshop.Api.Models.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workshop.Api.Models.JobInvoice", null)
                        .WithMany()
                        .HasForeignKey("JobInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workshop.Api.Models.JobServiceSelection", b =>
                {
                    b.HasOne("Workshop.Api.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workshop.Api.Models.ServiceCatalogItem", "ServiceCatalogItem")
                        .WithMany()
                        .HasForeignKey("ServiceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("ServiceCatalogItem");
                });

            modelBuilder.Entity("Workshop.Api.Models.WorklogEntry", b =>
                {
                    b.HasOne("Workshop.Api.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workshop.Api.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Workshop.Api.Models.Customer", b =>
                {
                    b.Navigation("ServicePrices");

                    b.Navigation("StaffMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
