using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workshop.Api.Migrations
{
    public partial class ConsolidateLegacyBootstrapSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS gmail_accounts (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email text NOT NULL,
                    refresh_token text NOT NULL,
                    access_token text NULL,
                    access_token_expires_at timestamptz NULL,
                    scope text NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    is_default boolean NOT NULL DEFAULT false,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_gmail_accounts_email
                    ON gmail_accounts(email);
                CREATE INDEX IF NOT EXISTS ix_gmail_accounts_is_default
                    ON gmail_accounts(is_default);

                CREATE TABLE IF NOT EXISTS gmail_message_logs (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    gmail_account_id bigint NULL,
                    gmail_account_email text NULL,
                    gmail_message_id text NOT NULL,
                    gmail_thread_id text NULL,
                    internal_date_ms bigint NULL,
                    direction text NOT NULL,
                    counterparty_email text NOT NULL,
                    from_address text NULL,
                    to_address text NULL,
                    subject text NULL,
                    body text NULL,
                    snippet text NULL,
                    correlation_id text NULL,
                    rfc_message_id text NULL,
                    references_header text NULL,
                    has_attachments boolean NOT NULL DEFAULT false,
                    attachments_json text NULL,
                    is_read boolean NOT NULL DEFAULT false,
                    read_at timestamptz NULL,
                    detected_po_number text NULL,
                    is_system_initiated boolean NOT NULL DEFAULT false,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS gmail_account_id bigint NULL;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS gmail_account_email text NULL;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS rfc_message_id text NULL;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS references_header text NULL;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS has_attachments boolean NOT NULL DEFAULT false;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS attachments_json text NULL;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS is_read boolean NOT NULL DEFAULT false;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS read_at timestamptz NULL;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS detected_po_number text NULL;
                ALTER TABLE gmail_message_logs ADD COLUMN IF NOT EXISTS is_system_initiated boolean NOT NULL DEFAULT false;
                DROP INDEX IF EXISTS ux_gmail_message_logs_message_id;
                CREATE UNIQUE INDEX IF NOT EXISTS ux_gmail_message_logs_account_message_id
                    ON gmail_message_logs(gmail_account_id, gmail_message_id);
                CREATE INDEX IF NOT EXISTS ix_gmail_message_logs_account_id
                    ON gmail_message_logs(gmail_account_id);
                CREATE INDEX IF NOT EXISTS ix_gmail_message_logs_thread_id
                    ON gmail_message_logs(gmail_thread_id);
                CREATE INDEX IF NOT EXISTS ix_gmail_message_logs_correlation_id
                    ON gmail_message_logs(correlation_id);

                CREATE TABLE IF NOT EXISTS inactive_gmail_correlations (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    correlation_id text NOT NULL,
                    reason text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_inactive_gmail_correlations_correlation_id
                    ON inactive_gmail_correlations(correlation_id);

                CREATE TABLE IF NOT EXISTS inventory_items (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_code text NOT NULL,
                    item_name text NOT NULL,
                    quantity numeric NULL,
                    purchases_description text NULL,
                    purchases_unit_price numeric NULL,
                    purchases_account text NULL,
                    purchases_tax_rate text NULL,
                    sales_description text NULL,
                    sales_unit_price numeric NULL,
                    sales_account text NULL,
                    sales_tax_rate text NULL,
                    inventory_asset_account text NULL,
                    cost_of_goods_sold_account text NULL,
                    status text NOT NULL,
                    inventory_type text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_items_item_code
                    ON inventory_items(item_code);
                CREATE INDEX IF NOT EXISTS ix_inventory_items_item_name
                    ON inventory_items(item_name);

                CREATE TABLE IF NOT EXISTS system_sync_state (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sync_key text NOT NULL,
                    last_synced_at timestamptz NULL,
                    last_result text NULL,
                    last_error text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_system_sync_state_sync_key
                    ON system_sync_state(sync_key);

                ALTER TABLE service_catalog_items ADD COLUMN IF NOT EXISTS personal_link_code text NULL;
                ALTER TABLE service_catalog_items ADD COLUMN IF NOT EXISTS dealership_link_code text NULL;
                CREATE INDEX IF NOT EXISTS ix_service_catalog_items_type_category
                    ON service_catalog_items(service_type, category);

                CREATE TABLE IF NOT EXISTS job_po_state (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id bigint NOT NULL,
                    correlation_id text NOT NULL,
                    counterparty_email text NULL,
                    status text NOT NULL,
                    requires_admin_attention boolean NOT NULL DEFAULT false,
                    admin_attention_reason text NULL,
                    confirmed_po_number text NULL,
                    detected_po_number text NULL,
                    first_request_sent_at timestamptz NULL,
                    last_request_sent_at timestamptz NULL,
                    last_follow_up_sent_at timestamptz NULL,
                    last_supplier_reply_at timestamptz NULL,
                    last_supplier_reply_message_id text NULL,
                    follow_up_count integer NOT NULL DEFAULT 0,
                    follow_up_enabled boolean NOT NULL DEFAULT true,
                    next_follow_up_due_at timestamptz NULL,
                    last_synced_at timestamptz NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_job_po_state_job_id
                    ON job_po_state(job_id);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_status
                    ON job_po_state(status);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_correlation_id
                    ON job_po_state(correlation_id);
                CREATE INDEX IF NOT EXISTS ix_job_po_state_next_follow_up_due_at
                    ON job_po_state(next_follow_up_due_at);

                ALTER TABLE xero_tokens ADD COLUMN IF NOT EXISTS tenant_name text NULL;
                ALTER TABLE xero_tokens ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
                ALTER TABLE xero_tokens ADD COLUMN IF NOT EXISTS is_default boolean NOT NULL DEFAULT false;
                DROP INDEX IF EXISTS ux_xero_tokens_provider;
                CREATE UNIQUE INDEX IF NOT EXISTS ux_xero_tokens_provider_tenant_id
                    ON xero_tokens(provider, tenant_id);
                CREATE INDEX IF NOT EXISTS ix_xero_tokens_is_default
                    ON xero_tokens(is_default);

                ALTER TABLE wof_fail_reasons ADD COLUMN IF NOT EXISTS code text;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE IF EXISTS wof_fail_reasons DROP COLUMN IF EXISTS code;
                DROP TABLE IF EXISTS job_po_state;
                DROP TABLE IF EXISTS system_sync_state;
                DROP TABLE IF EXISTS inventory_items;
                DROP TABLE IF EXISTS inactive_gmail_correlations;
                DROP TABLE IF EXISTS gmail_message_logs;
                DROP TABLE IF EXISTS gmail_accounts;
                """);
        }
    }
}
