using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workshop.Api.Migrations
{
    public partial class AddEStationMonitoring : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS light_stations (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    station_id VARCHAR(32) NOT NULL,
                    mac VARCHAR(64),
                    alias VARCHAR(160),
                    is_online BOOLEAN NOT NULL DEFAULT FALSE,
                    last_heartbeat_at TIMESTAMP WITH TIME ZONE,
                    server_address VARCHAR(255),
                    firmware_version VARCHAR(80),
                    total_count INTEGER NOT NULL DEFAULT 0,
                    send_count INTEGER NOT NULL DEFAULT 0,
                    last_payload_status VARCHAR(40) NOT NULL DEFAULT 'Processed',
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_light_stations_station_id ON light_stations (station_id);
                CREATE INDEX IF NOT EXISTS ix_light_stations_last_heartbeat_at ON light_stations (last_heartbeat_at);

                CREATE TABLE IF NOT EXISTS light_tags (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tag_id VARCHAR(32) NOT NULL,
                    station_id VARCHAR(32),
                    current_group INTEGER,
                    current_color VARCHAR(40),
                    is_light_on BOOLEAN NOT NULL DEFAULT FALSE,
                    is_flashing BOOLEAN,
                    battery_raw INTEGER,
                    battery_voltage NUMERIC(4,1),
                    battery_percent INTEGER,
                    rf_power_send INTEGER,
                    rf_power_recv INTEGER,
                    firmware_version VARCHAR(80),
                    last_result_type INTEGER,
                    last_seen_at TIMESTAMP WITH TIME ZONE,
                    last_payload_status VARCHAR(40) NOT NULL DEFAULT 'Processed',
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_light_tags_tag_id ON light_tags (tag_id);
                CREATE INDEX IF NOT EXISTS ix_light_tags_station_id ON light_tags (station_id);
                CREATE INDEX IF NOT EXISTS ix_light_tags_current_group ON light_tags (current_group);
                CREATE INDEX IF NOT EXISTS ix_light_tags_last_seen_at ON light_tags (last_seen_at);

                CREATE TABLE IF NOT EXISTS mqtt_message_logs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    topic VARCHAR(512) NOT NULL,
                    payload TEXT NOT NULL,
                    message_type VARCHAR(40) NOT NULL,
                    station_id VARCHAR(32),
                    tag_id VARCHAR(32),
                    received_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    processing_status VARCHAR(40) NOT NULL,
                    error_message TEXT
                );

                CREATE INDEX IF NOT EXISTS ix_mqtt_message_logs_received_at ON mqtt_message_logs (received_at);
                CREATE INDEX IF NOT EXISTS ix_mqtt_message_logs_station_received_at ON mqtt_message_logs (station_id, received_at);
                CREATE INDEX IF NOT EXISTS ix_mqtt_message_logs_type_received_at ON mqtt_message_logs (message_type, received_at);
                CREATE INDEX IF NOT EXISTS ix_mqtt_message_logs_status_received_at ON mqtt_message_logs (processing_status, received_at);
            """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS mqtt_message_logs;
                DROP TABLE IF EXISTS light_tags;
                DROP TABLE IF EXISTS light_stations;
            """);
        }
    }
}
