using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workshop.Api.Migrations;

public partial class AddJobWofState : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS job_wof_state (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id bigint NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                manual_status text NULL,
                created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ux_job_wof_state_job_id ON job_wof_state(job_id);
            
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'jobs'
                      AND column_name = 'wof_manual_status'
                ) THEN
                    INSERT INTO job_wof_state (job_id, manual_status, created_at, updated_at)
                    SELECT j.id, j.wof_manual_status, date_trunc('milliseconds', now()), date_trunc('milliseconds', now())
                    FROM jobs AS j
                    WHERE j.wof_manual_status IS NOT NULL
                      AND NOT EXISTS (
                        SELECT 1
                        FROM job_wof_state AS s
                        WHERE s.job_id = j.id
                    );

                    ALTER TABLE jobs DROP COLUMN IF EXISTS wof_manual_status;
                END IF;
            END $$;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS wof_manual_status text;

            UPDATE jobs AS j
            SET wof_manual_status = s.manual_status
            FROM job_wof_state AS s
            WHERE s.job_id = j.id
              AND s.manual_status IS NOT NULL;

            DROP TABLE IF EXISTS job_wof_state;
            """);
    }
}
