import type { WorklogEntry, WorklogJob, WorklogStaffProfile } from "./types";

export const worklogStaffProfiles: WorklogStaffProfile[] = [
  { id: "1", name: "张三", role: "Technician", cost_rate: 45 },
  { id: "2", name: "李四", role: "Technician", cost_rate: 50 },
  { id: "3", name: "王五", role: "Supervisor", cost_rate: 65 },
  { id: "4", name: "赵六", role: "Admin", cost_rate: 35 },
 
];

export const worklogJobs: WorklogJob[] = [
  { id: "1", rego: "ABC123", note: "前保险杠喷漆", created_date: "2026-02-15", makeModel: "Toyota Corolla", panels: 2, customerCode: "C001" },
  { id: "2", rego: "XYZ789", note: "全车抛光处理", created_date: "2026-02-18", makeModel: "Honda Civic", panels: 3, customerCode: "C014" },
  { id: "3", rego: "DEF456", note: "后门拆装修复", created_date: "2026-02-20", makeModel: "Mazda 3", panels: 1, customerCode: "C020" },
  { id: "4", rego: "GHI321", note: "左侧翼子板打磨喷漆", created_date: "2026-02-22", makeModel: "Nissan X-Trail", panels: 2, customerCode: "C032" },
  { id: "5", rego: "JKL654", note: "引擎盖修复", created_date: "2026-02-25", makeModel: "Ford Ranger", panels: 1, customerCode: "C041" },
  { id: "6", rego: "MNO987", note: "全车检查保养", created_date: "2026-02-28", makeModel: "Hyundai i30", customerCode: "C055" },
  { id: "7", rego: "ABC456", note: "车门钣金修复", created_date: "2026-03-01", makeModel: "Kia Sportage", panels: 2, customerCode: "C063" },
  { id: "8", rego: "PQR111", note: "后视镜更换", created_date: "2026-03-02", makeModel: "Subaru Forester", customerCode: "C077" },
];

export const initialWorklogEntries: WorklogEntry[] = [
  {
    id: "1",
    staff_name: "张三",
    team: "维修组A",
    role: "Technician",
    rego: "ABC123",
    job_id: "1",
    job_note: "前保险杠喷漆",
    task_types: ["喷漆"],
    work_date: "2026-03-01",
    start_time: "09:00",
    end_time: "11:30",
    cost_rate: 45,
    admin_note: "按计划完成",
    source: "tech",
    created_at: "2026-03-01 09:00:00",
    created_by: "system",
    flags: [],
  },
  {
    id: "2",
    staff_name: "张三",
    team: "维修组A",
    role: "Technician",
    rego: "ABC123",
    job_id: "1",
    job_note: "前保险杠喷漆",
    task_types: ["喷漆", "打磨"],
    work_date: "2026-03-01",
    start_time: "09:30",
    end_time: "11:00",
    cost_rate: 45,
    admin_note: "可能重复",
    source: "admin",
    created_at: "2026-03-01 15:00:00",
    created_by: "admin",
    flags: ["duplicate", "overlap"],
  },
  {
    id: "3",
    staff_name: "李四",
    team: "维修组A",
    role: "Technician",
    rego: "XYZ789",
    job_id: "2",
    job_note: "全车抛光处理",
    task_types: ["抛光"],
    work_date: "2026-03-01",
    start_time: "08:00",
    end_time: "12:00",
    cost_rate: 50,
    admin_note: "",
    source: "tech",
    created_at: "2026-03-01 08:00:00",
    created_by: "system",
    flags: [],
  },
  {
    id: "4",
    staff_name: "王五",
    team: "维修组B",
    role: "Supervisor",
    rego: "DEF456",
    job_id: "3",
    job_note: "后门拆装修复",
    task_types: ["拆装", "检查"],
    work_date: "2026-03-02",
    start_time: "10:00",
    end_time: "15:30",
    cost_rate: 65,
    admin_note: "长时间作业",
    source: "admin",
    created_at: "2026-03-02 10:00:00",
    created_by: "admin",
    flags: ["long_session"],
  },
  {
    id: "5",
    staff_name: "赵六",
    team: "行政部",
    role: "Admin",
    rego: "GHI321",
    job_id: "4",
    job_note: "左侧翼子板打磨喷漆",
    task_types: ["检查"],
    work_date: "2026-03-02",
    start_time: "09:00",
    end_time: "10:00",
    cost_rate: 35,
    admin_note: "质量检查",
    source: "admin",
    created_at: "2026-03-02 09:00:00",
    created_by: "admin",
    flags: [],
  },
  {
    id: "6",
    staff_name: "李四",
    team: "维修组A",
    role: "Technician",
    rego: "JKL654",
    job_id: "5",
    job_note: "引擎盖修复",
    task_types: ["打磨", "喷漆"],
    work_date: "2026-03-02",
    start_time: "13:00",
    end_time: "17:00",
    cost_rate: 50,
    admin_note: "",
    source: "tech",
    created_at: "2026-03-02 13:00:00",
    created_by: "system",
    flags: [],
  },
  {
    id: "7",
    staff_name: "孙七",
    team: "维修组B",
    role: "Technician",
    rego: "MNO987",
    job_id: "6",
    job_note: "全车检查保养",
    task_types: ["检查", "清洁"],
    work_date: "2026-03-03",
    start_time: "08:30",
    end_time: "11:00",
    cost_rate: 48,
    admin_note: "定期保养",
    source: "tech",
    created_at: "2026-03-03 08:30:00",
    created_by: "system",
    flags: [],
  },
];
