import type { WorklogEntry, WorklogJob, WorklogStaffProfile } from "./types";

export const worklogStaffProfiles: WorklogStaffProfile[] = [
  { id: "1", name: "Zhang San", role: "Technician", cost_rate: 45 },
  { id: "2", name: "John Doe", role: "Technician", cost_rate: 50 },
  { id: "3", name: "Wang Wu", role: "Supervisor", cost_rate: 65 },
  { id: "4", name: "Zhao Liu", role: "Admin", cost_rate: 35 },
 
];

export const worklogJobs: WorklogJob[] = [
  { id: "1", rego: "ABC123", note: "Front bumper painting", created_date: "2026-02-15", makeModel: "Toyota Corolla", panels: 2, customerCode: "C001" },
  { id: "2", rego: "XYZ789", note: "Full car polishing", created_date: "2026-02-18", makeModel: "Honda Civic", panels: 3, customerCode: "C014" },
  { id: "3", rego: "DEF456", note: "Rear door disassembly and repair", created_date: "2026-02-20", makeModel: "Mazda 3", panels: 1, customerCode: "C020" },
  { id: "4", rego: "GHI321", note: "Left fender polished and painted", created_date: "2026-02-22", makeModel: "Nissan X-Trail", panels: 2, customerCode: "C032" },
  { id: "5", rego: "JKL654", note: "hood repair", created_date: "2026-02-25", makeModel: "Ford Ranger", panels: 1, customerCode: "C041" },
  { id: "6", rego: "MNO987", note: "Full vehicle inspection and maintenance", created_date: "2026-02-28", makeModel: "Hyundai i30", customerCode: "C055" },
  { id: "7", rego: "ABC456", note: "Door sheet metal repair", created_date: "2026-03-01", makeModel: "Kia Sportage", panels: 2, customerCode: "C063" },
  { id: "8", rego: "PQR111", note: "Rear view mirror replacement", created_date: "2026-03-02", makeModel: "Subaru Forester", customerCode: "C077" },
];

export const initialWorklogEntries: WorklogEntry[] = [
  {
    id: "1",
    staff_name: "Zhang San",
    team: "Maintenance Group A",
    role: "Technician",
    rego: "ABC123",
    job_id: "1",
    job_note: "Front bumper painting",
    task_types: ["spray paint"],
    work_date: "2026-03-01",
    start_time: "09:00",
    end_time: "11:30",
    cost_rate: 45,
    admin_note: "Completed as planned",
    source: "tech",
    created_at: "2026-03-01 09:00:00",
    created_by: "system",
    flags: [],
  },
  {
    id: "2",
    staff_name: "Zhang San",
    team: "Maintenance Group A",
    role: "Technician",
    rego: "ABC123",
    job_id: "1",
    job_note: "Front bumper painting",
    task_types: ["spray paint", "polish"],
    work_date: "2026-03-01",
    start_time: "09:30",
    end_time: "11:00",
    cost_rate: 45,
    admin_note: "possible duplicate",
    source: "admin",
    created_at: "2026-03-01 15:00:00",
    created_by: "admin",
    flags: ["duplicate", "overlap"],
  },
  {
    id: "3",
    staff_name: "John Doe",
    team: "Maintenance Group A",
    role: "Technician",
    rego: "XYZ789",
    job_id: "2",
    job_note: "Full car polishing",
    task_types: ["polishing"],
    work_date: "2026-03-01",
    start_time: "08:00",
    end_time: "12:00",
    cost_rate: 50,
    admin_note: "",
    source: "tech",
    created_at: "2026-03-01 08:00:00",
    created_by: "system",
    flags: [],
  },
  {
    id: "4",
    staff_name: "Wang Wu",
    team: "Maintenance Group B",
    role: "Supervisor",
    rego: "DEF456",
    job_id: "3",
    job_note: "Rear door disassembly and repair",
    task_types: ["Disassembly and assembly", "examine"],
    work_date: "2026-03-02",
    start_time: "10:00",
    end_time: "15:30",
    cost_rate: 65,
    admin_note: "Long working hours",
    source: "admin",
    created_at: "2026-03-02 10:00:00",
    created_by: "admin",
    flags: ["long_session"],
  },
  {
    id: "5",
    staff_name: "Zhao Liu",
    team: "Administration Department",
    role: "Admin",
    rego: "GHI321",
    job_id: "4",
    job_note: "Left fender polished and painted",
    task_types: ["examine"],
    work_date: "2026-03-02",
    start_time: "09:00",
    end_time: "10:00",
    cost_rate: 35,
    admin_note: "Quality check",
    source: "admin",
    created_at: "2026-03-02 09:00:00",
    created_by: "admin",
    flags: [],
  },
  {
    id: "6",
    staff_name: "John Doe",
    team: "Maintenance Group A",
    role: "Technician",
    rego: "JKL654",
    job_id: "5",
    job_note: "hood repair",
    task_types: ["polish", "spray paint"],
    work_date: "2026-03-02",
    start_time: "13:00",
    end_time: "17:00",
    cost_rate: 50,
    admin_note: "",
    source: "tech",
    created_at: "2026-03-02 13:00:00",
    created_by: "system",
    flags: [],
  },
  {
    id: "7",
    staff_name: "Sun Qi",
    team: "Maintenance Group B",
    role: "Technician",
    rego: "MNO987",
    job_id: "6",
    job_note: "Full vehicle inspection and maintenance",
    task_types: ["examine", "clean"],
    work_date: "2026-03-03",
    start_time: "08:30",
    end_time: "11:00",
    cost_rate: 48,
    admin_note: "Regular maintenance",
    source: "tech",
    created_at: "2026-03-03 08:30:00",
    created_by: "system",
    flags: [],
  },
];
